### PR TITLE
Moving towards 1.1.0

### PR DESCRIPTION
**Pull request by infertux**
New unified branch from #15

### CODE REVIEW

**Comment by infertux** [comment]
Alright, after hours of trial and error, I think I finally got something working for both multipart and non-multipart (plain) messages. It's working on my setup (Python 2 and Thunderbird/Mutt).

It'd be awesome if you could try [this version](https://raw.githubusercontent.com/infertux/zeyple/moving-towards-1.1.0/zeyple/zeyple.py) on your setup @Nithanim and let us know if it works :smiley:

/cc @acatton

**Comment by Nithanim** [comment]
"It works!" as some webservers would say - flawlessly as far as I can tell with my quick tests! I hope to be able to have a closer look at it tomorrow. You are both truly my heroes :)

**Comment by infertux** [comment]
Great news! Thanks. I'll test it more thoroughly too but I think we're on the home stretch :)

**Comment by Nithanim** [comment]
I discovered that it is still not a good idea to send already encrypted mails through zeyple. I think last time thunderbird simply could not decrypt it but now that mail kills it. Might need an additional issue for that at some point :)

**Comment by Nithanim** [comment]
So today I tried sending mails with the php mail function (assumed; built into the application I am using) which could not be decrypted by thunderbird :( (investigating that later). I then tried to send it to an email without keys but that resulted in an exception. I am using the version you posted above.
```
postfix log:
------------------------------
Aug 31 18:29:29 vps108 postfix/pickup[32139]: B22DF44118: uid=33 from=<myMailAddrThatHasAKey>
Aug 31 18:29:29 vps108 postfix/cleanup[2569]: B22DF44118: message-id=<ad95122a9955e58f80786858e452c8e8@@@www.nithanim.me>
Aug 31 18:29:29 vps108 postfix/qmgr[3342]: B22DF44118: from=<myMailAddrThatHasAKey>, size=641, nrcpt=1 (queue active)
Aug 31 18:29:30 vps108 postfix/pipe[2571]: B22DF44118: to=<mailWithoutKey>, relay=zeyple, delay=0.3, delays=0.07/0.01/0/0.21, dsn=5.3.0, status=bounced (Command died with status 1: "/usr/local/bin/zeyple.py". Command output: Traceback (most recent call last):   File "/usr/local/bin/zeyple.py", line 244, in <module>     zeyple.process_message(message, recipients)   File "/usr/local/bin/zeyple.py", line 142, in process_message     self._add_zeyple_header(out_message) UnboundLocalError: local variable 'out_message' referenced before assignment )
Aug 31 18:29:30 vps108 postfix/cleanup[2569]: 00A334411C: message-id=<20150831182930.00A334411C@@@mail.nithanim.me>
Aug 31 18:29:30 vps108 postfix/bounce[2586]: B22DF44118: sender non-delivery notification: 00A334411C
Aug 31 18:29:30 vps108 postfix/qmgr[3342]: 00A334411C: from=<>, size=3082, nrcpt=1 (queue active)
Aug 31 18:29:30 vps108 postfix/qmgr[3342]: B22DF44118: removed
Aug 31 18:29:32 vps108 postfix/smtp[2587]: 00A334411C: to=<myMailAddrThatHasAKey>, relay=mx-eu.mail.am0.yahoodns.net[188.125.69.79]:25, delay=2.1, delays=0/0.01/0.08/2, dsn=2.0.0, status=sent (250 ok dirdel)
Aug 31 18:29:32 vps108 postfix/qmgr[3342]: 00A334411C: removed
------------------------------


zeyple log:
------------------------------
2015-08-31 18:29:29,876 2572 INFO Zeyple ready to encrypt outgoing emails
2015-08-31 18:29:29,878 2572 INFO Processing outgoing message <ad95122a9955e58f80786858e452c8e8@@@www.nithanim.me>
2015-08-31 18:29:29,878 2572 INFO Recipient: nithanim@@@gmail.com
2015-08-31 18:29:29,878 2572 INFO Trying to encrypt for nithanim@@@gmail.com
2015-08-31 18:29:29,968 2572 INFO Key ID: None
2015-08-31 18:29:29,969 2572 WARNING No keys found, message will be sent unencrypted
------------------------------
```
I am not sure if this is helpful to you. I will try to provide more details if necessary.

PS: I tripled all '@' because of bots.

**Comment by infertux** [comment]
@Nithanim

> I discovered that it is still not a good idea to send already encrypted mails through zeyple. I think last time thunderbird simply could not decrypt it but now that mail kills it. Might need an additional issue for that at some point :)

Wow! This is impressive if it manages to kill Thunderbird :). I'll let you open a new issue for that if it's still happening with the new version (see below).

>  I tried sending mails with the php mail function (assumed; built into the application I am using) which could not be decrypted by thunderbird :( (investigating that later). I then tried to send it to an email without keys but that resulted in an exception. I am using the version you posted above.

Yup, there was a silly error that would make it break when no keys were found for the recipient. It should be fixed now.

I'll let you test the [latest version](https://raw.githubusercontent.com/infertux/zeyple/moving-towards-1.1.0/zeyple/zeyple.py) and if everything looks good, I'll make a proper release. Finally! :smile:

**Comment by Nithanim** [comment]
Glad you are back! I actually remembered today (actually yesterday by now^^) that I had still issues and thought about bumping this thread. I am firing up vagrant right now because I am unable to test it in production easily :)
As far as the thunderbird issue is concerned: I never investigated the issue any further but if I encounter it again, I will.

**Comment by Nithanim** [comment]
My vagrant-box is somehow broken on multiple ends, so I am no going to use that :( However, it seems that recipients without a key now receive emails! :D Thank you!

**Comment by acatton** [comment]
Thanks for merging that @infertux .

**Comment by infertux** [comment]
Thanks a lot for your help @acatton ;)

**Pull request merged**
